name: CI

env:
  GH_TOKEN: ${{ github.token }}

on:
  push:
    branches: [main, develop]
    tags: ['*']
  pull_request:
    branches: [main, develop]

jobs:
  test:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

  build:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build app
        run: bun run build:prod

      - name: Build Electron for ${{ matrix.os }}
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            bunx electron-builder build --publish=never --linux
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            bunx electron-builder build --publish=never --win
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            bunx electron-builder build --publish=never --mac
          fi

      - name: Upload Linux files
        uses: actions/upload-artifact@v4
        with:
          name: opencode-ui-linux
          path: |
            release/*.AppImage
            release/*.deb
            release/*.rpm
        if: matrix.os == 'ubuntu-latest'

      - name: Upload MacOS file
        uses: actions/upload-artifact@v4
        with:
          name: opencode-ui-mac
          path: release/*.dmg
        if: matrix.os == 'macos-latest'

      - name: Upload Windows file
        uses: actions/upload-artifact@v4
        with:
          name: opencode-ui-windows
          path: release/*.exe
        if: matrix.os == 'windows-latest'

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Linux files
        uses: actions/download-artifact@v4
        with:
          name: opencode-ui-linux
          path: artifacts/linux

      - name: Download MacOS files
        uses: actions/download-artifact@v4
        with:
          name: opencode-ui-mac
          path: artifacts/mac

      - name: Download Windows files
        uses: actions/download-artifact@v4
        with:
          name: opencode-ui-windows
          path: artifacts/windows

      - name: create release
        run: gh release create ${{ github.ref_name }} --generate-notes

      - name: upload linux files to release
        run: gh release upload ${{ github.ref_name }} artifacts/linux/*.AppImage artifacts/linux/*.deb artifacts/linux/*.rpm

      - name: upload mac file to release
        run: gh release upload ${{ github.ref_name }} artifacts/mac/*.dmg

      - name: upload windows file to release
        run: gh release upload ${{ github.ref_name }} artifacts/windows/*.exe

  aur-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Setup pacman
        run: pacman -Syu --noconfirm base-devel git openssh

      - name: Setup SSH for AUR
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_KEY }}" > ~/.ssh/aur_key
          chmod 600 ~/.ssh/aur_key
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          git config --global core.sshCommand "ssh -i ~/.ssh/aur_key -o StrictHostKeyChecking=no"

      - name: Checkout AUR repo
        run: git clone ssh://aur@aur.archlinux.org/opencode-ui-bin.git aur

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Download Linux files
        uses: actions/download-artifact@v4
        with:
          name: opencode-ui-linux
          path: artifacts/linux

      - name: Calculate sha256sum
        id: sha256
        run: |
          cd artifacts/linux
          SHA=$(sha256sum opencode-ui-*.AppImage | cut -d' ' -f1)
          echo "sha256=$SHA" >> $GITHUB_OUTPUT

      - name: Update PKGBUILD
        run: |
          cd aur
          sed -i "s/pkgver=.*/pkgver=${{ steps.version.outputs.version }}/" PKGBUILD
          sed -i "s/sha256sums=.*/sha256sums=('${{ steps.sha256.outputs.sha256 }}')/" PKGBUILD
          sed -i "s/pkgrel=.*/pkgrel=1/" PKGBUILD

      - name: Generate .SRCINFO
        run: |
          cd aur
          makepkg --printsrcinfo > .SRCINFO

      - name: Commit and push to AUR
        run: |
          cd aur
          git config user.email "contact@marmotz.dev"
          git config user.name "Marmotz"
          git add PKGBUILD .SRCINFO
          git commit -m "Update to ${{ steps.version.outputs.version }}"
          git push
